name: Shuttle Status

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0/3 * * *'

jobs:
  status:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: cargo install cargo-shuttle
    - name: Clone
      run: git clone https://github.com/Theboiboi8/kamela-bot.git
    - name: CD
      run: cd kamela-bot
    - name: Status
      run: cargo shuttle project status
