name: Shuttle Status

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0/3 * * *'

jobs:
  status:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: cargo install cargo-shuttle
    - name: Login
      run: cargo shuttle login --api-key ${{ secrets.SHUTTLE_API_KEY }}
    - name: Status
      run: cargo shuttle project restart
